---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: om
  type: git
  source:
    uri: git@github.com:pivotal-cf/om.git
    branch: master
    ignore_paths:
    - version
    - README.md
    - docs
    private_key: ((om.private_key))

- name: om-pr
  type: pull-request
  source:
    repo: pivotal-cf/om
    access_token: ((om.access_token))

- name: om-version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: git@github.com:pivotal-cf/om.git
    branch: master
    file: version
    private_key: ((om.private_key))

- name: om-release
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((om.access_token))

jobs:
- name: test-om
  plan:
  - aggregate:
    - get: om
      trigger: true
  - task: test
    file: om/ci/tasks/tests/task.yml
  - task: write-readme
    file: om/ci/tasks/readme/task.yml
  - put: om
    params:
      repository: om-updated-readme/om
      rebase: true

- name: test-om-pr
  public: true
  plan:
  - get: om
  - get: om-pr
    trigger: true
    version: every
  - put: om-pr
    params:
      path: om-pr
      status: pending
  - task: unit-test
    input_mapping:
      om: om-pr
    file: om/ci/tasks/tests/task.yml
    on_failure:
      put: om-pr
      params:
        path: om-pr
        status: failure
    on_success:
      put: om-pr
      params:
        path: om-pr
        status: success

- name: release-om
  plan:
  - aggregate:
    - get: om
      passed:
      - test-om
    - get: om-version
      params:
        bump: minor
  - task: build
    file: om/ci/tasks/build/task.yml
  - put: om-release
    params:
      name: om-version/number
      tag: om-version/number
      globs:
      - binaries/om-*
  - put: om-version
    params:
      bump: minor