# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
release:
  github:
    owner: pivotal-cf
    name: om
  draft: true
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w -X "main.version={{.Env.OM_VERSION}}"
archives:
- format: binary
  name_template: "om-{{ .Os }}"
brews:
- github:
    owner: pivotal-cf
    name: om
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
